### PR TITLE
fix spelling

### PR DESCRIPTION
**Pull request by TheDalaiAlpaca**

### CODE REVIEW

**Comment by 3unjee** [comment]
Ahah, good one. Thank you !

**Comment by 3unjee** [comment]
@TheDalaiAlpaca, could you provide your public mail for the AUTHORS file ?

**Comment by TheDalaiAlpaca** [comment]
Sure! It is dleeg@tutanota.com. Thanks for listing me

**Comment by 3unjee** [comment]
https://github.com/omega-gg/MotionBox/commit/a3930f9d2e0ae67f696b280d316424867bdd3d8a

**Pull request merged**
